name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Télécharger LocalXpose
        run: Invoke-WebRequest -Uri https://localxpose.io/downloads/latest/localxpose-windows-amd64.zip -OutFile localxpose.zip

      - name: Extraire LocalXpose
        run: Expand-Archive -Path localxpose.zip -DestinationPath .\localxpose

      - name: Authentifier LocalXpose
        run: .\localxpose\lx.exe authtoken $Env:LOCALXPOSE_TOKEN
        env:
          LOCALXPOSE_TOKEN: ${{ secrets.LOCALXPOSE_TOKEN }}

      - name: Activer le bureau à distance
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

      - name: Activer le pare-feu pour le bureau à distance
        run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop" -ErrorAction Stop

      - name: Définir le mot de passe pour runneradmin
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Démarrer le tunnel LocalXpose sur le port 3000
        run: .\localxpose\lx.exe http 3000 --name "MonTunnelLocalhost3000"
